[package]
name = "rise_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rich-presence = "0.2.3"
osascript = "0.3.0"
tokio = { version = "1.36.0", features = ["full"] }
